### ISSUE TITLE
setup.py will crash

### ISSUE THREAD

**Issue by soldierxue** [awslabs/amazon-ecs-java-microservices#1]
A few grammar not compatiable with python3.x like:

(1)service_list.keys().index(service) AttributeError: 'dict_keys' object has no attribute 'index'
(2) after encode('utf-8') python will not treat it as str

And this script create 3 subnets across 3 AZs, so if your target region only have 2 AZs, it will be failed.

**Comment by zachahuy-zz** [comment]
please use python 2
