### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by SyCode7** [awslabs/amazon-ecs-java-microservices#3]
I think you might want to correct the third part i.e. CI/CD  to "Part Three" and also correct the corresponding url to `https://github.com/awslabs/amazon-ecs-java-microservices/tree/master/3_ECS_Java_Spring_PetClinic_CICD`

**Comment by tdhulster** [comment]
Added PR for this one #4

**Comment by SyCode7** [comment]
thanks !

**Comment by tdhulster** [comment]
Yw! PR has been merged and closed so this issue can be closed as well ;)

**Comment by SyCode7** [comment]
thanks... closing.
